version: '3.3'
services:
  adminer:
    image: adminer:latest
    ports:
      - 9081:8080
    networks:
      - webnet
  postgres:
    image: postgres:11
    volumes:
      - data-volume:/data/db
    ports:
      - ${DATABASE_PORT}:5432
    environment:
      POSTGRES_PASSWORD: ${DATABASE_PASSWORD}
      POSTGRES_USER: ${DATABASE_USER}
      POSTGRES_DB: ${DATABASE_NAME}
    networks:
      - webnet
networks:
  webnet:
volumes:
  data-volume:
