// src/constants/Constants.ts
export default {
  CANDLE_TYPE: {
    DRAGONFLY_DOJI: 'Dragonfly Doji',
    GRAVE_STONE_DOJI: 'Grave Stone Doji',
    DOJI: 'Doji',
    BEARISH_MARUBORU: 'Bearish Marubozu',
    BEARISH_SPRINNING_TOP: 'Bearish Spinning Top',
    BEARISH_HAMMER_STICK: 'Bearish Hammer Stick',
    BEARISH_INVERT_HAMMER_STICK: 'Bearish Inverted Hammer Stick',
    BULLISH_MARUBORU: 'Bullish Marubozu',
    BULLISH_SPRINNING_TOP: 'Bullish Spinning Top',
    BULLISH_HAMMER_STICK: 'Bullish Hammer Stick',
    BULLISH_INVERT_HAMMER_STICK: 'Bullish Inverted Hammer Stick',
  },
  HARMONIC_PATTERN: {
    BULLISH_CYPHER: 'Bullish Cypher',
    BEARISH_CYPHER: 'Bearish Cypher',
    BULLISH_BAT: 'Bullish Bat',
    BEARISH_BAT: 'Bearish Bat',
    BULLISH_GARTLEY: 'Bullish Gartley',
    BEARISH_GARTLEY: 'Bearish Gartley',
    BULLISH_BUTTERFLY: 'Bullish Butterfly',
    BEARISH_BUTTERFLY: 'Bearish Butterfly',
    BULLISH_CRAB: 'Bullish Crab',
    BEARISH_CRAB: 'Bearish Crab',
    BULLISH_SHARK: 'Bullish Shark',
    BEARISH_SHARK: 'Bearish Shark',
  },
  UNKNOWN: 'unknown',
};